######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 3 09:52:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=xml
# Input
HEADERS += encryptor.h meeting.h meetingmgr.h mtime.h xmleditor.h
SOURCES += main.cpp encryptor.cpp meetingmgr.cpp xmleditor.cpp
