######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 2 16:10:31 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=xml

# Input
HEADERS += meeting.h \
           meetingmgr.h \
           xmleditor.h \
           encryptor.h \
           mtime.h
SOURCES += meetingmgr.cpp \
           encryptor.cpp \
           xmleditor.cpp
